version: '3'
services:
    node:
        build:
            context: .
            args:
                NPM_TOKEN: ${NPM_TOKEN}
        ports:
            - ${PORT}:${PORT}
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
volumes:
    mongodb:
